import { FunctionComponent } from 'react';
import { AdminLayoutProps } from './AdminLayout.props';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import { UserHead } from '@/components/UserHead/UserHead';
import Head from 'next/head';

const AdminLayout = ({ children }: AdminLayoutProps): JSX.Element => {
	return (
		<>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>

			<UserHead userName={'Admin'} />
			<Sidebar />

			<main>{children}</main>
		</>
	);
};

export const withAdminLayout = <T extends Record<string, unknown>>(Component: FunctionComponent<T>) => {
	return function withLayoutComponent(props: T): JSX.Element {
		return (
			<AdminLayout>
				<Component {...props} />
			</AdminLayout>
		);
	};
};
