import Head from 'next/head';
import { Home } from '.';

export default function Admin() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main>
				<h1>Admin page</h1>

				<Home />
			</main>
		</>
	);
}
