import { Facilities } from '@/components/Sections/Facilities/Facilities';
import { FindApartment } from '@/components/Sections/FindApartment/FindApartment';
import { Offers } from '@/components/Sections/Offers/Offers';
import { Rooms } from '@/components/Sections/Rooms/Rooms';
import { Welcome } from '@/components/Sections/Welcome/Welcome';
import { APIUrls } from '@/configs/api.config';
import { addCurrentPageLang, addRoomPages, createMainPage } from '@/features/pages/pagesSlice';
import { IMainPage } from '@/interfaces/MainPage.interface';
import { IRoomPage } from '@/interfaces/RoomPage.interface';
import { withMainPageLayout } from '@/layout/MainPageLayout/MainPageLayout';
import axios from 'axios';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';

export function Home(): JSX.Element {
	const dispatch = useDispatch();

	useEffect(() => {
		(async () => {
			try {
				const { data: MainPageData } = await axios.get<IMainPage>(APIUrls.MainPage);
				const { data: RoomPagesData } = await axios.get<IRoomPage[]>(APIUrls.RoomPages);

				dispatch(createMainPage(MainPageData));
				dispatch(addRoomPages(RoomPagesData));
			} catch (ex) {
				console.error(ex);
			}
		})();
	}, []);

	return (
		<>
			<Head>
				<title>Luxury Hotel</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Welcome />
				<FindApartment />
				<Rooms />
				<Facilities />
				<Offers />
			</main>
		</>
	);
}

export default withMainPageLayout(Home);
