import Head from 'next/head';
import { withLayout } from '@/layout/Layout';
import { Welcome } from '@/components/Sections/Welcome/Welcome';
import { FindApartment } from '@/components/Sections/FindApartment/FindApartment';

export function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Welcome />
				<FindApartment />
			</main>
		</>
	);
}

export default withLayout(Home);
